# Generated by Django 5.1 on 2025-08-08 20:06

from django.db import migrations,models

class Migration(migrations.Migration):
    dependencies = [
        ('tracking', '0001_initial'),  # Remplace par le nom de ta dernière migration
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='vehicle',
            field=models.CharField(max_length=50),
        ),
    ]
