# Generated by Django 5.1 on 2025-08-08 20:14

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20250808_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='path',
            field=models.JSONField(),
        ),
    ]
