# Generated by Django 5.1 on 2025-08-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20250808_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='path',
            field=models.JSONField(db_column='data'),
        ),
        migrations.AlterModelTable(
            name='history',
            table='tracking_history',
        ),
    ]
