# Generated by Django 5.1 on 2025-08-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(default='LILYGO-GPS-001', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_by_sms', models.BooleanField(default=True)),
            ],
        ),
    ]
