# Generated by Django 5.1 on 2025-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_smsposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Alerte', 'verbose_name_plural': 'Alertes'},
        ),
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('out_of_geofence', 'Hors zone'), ('speeding', 'Excès de vitesse'), ('no_signal', 'Perte de signal GPS'), ('maintenance', 'Maintenance requise'), ('ignition_on', 'Démarrage du véhicule'), ('ignition_off', 'Arrêt du véhicule')], max_length=100),
        ),
    ]
